# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - pwd
install:
  ## install samtools
  - echo 'here';
  - pwd 
  - wget https://github.com/samtools/samtools/releases/download/1.6/samtools-1.6.tar.bz2
  - tar -vxjf samtools-1.6.tar.bz2
  - cd samtools-1.6
  - make
  - sudo make install; cd 
  - echo 'where now';
  - pwd
  - ./travis-tool.sh install_bioc_deps
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github r-lib/testthat
  - ./travis-tool.sh install_github mskilab/gUtils
  - ./travis-tool.sh install_github r-lib/covr
  
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
